init:
  dt: 0.01
  t_span: [0, 500]
  R0: [0, 60e3, 10e3]
  V0: [0, -100, 0]


G_LIMIT: 14.0


guidance:
  vars:
    START_RANGE: 40e3
    OFFSET: -pi
    MAG: 2

  phase:
    0:
      condition_next: range <= START_RANGE + 2e3
    1:
      pronav:
        TARGET: [2e3, START_RANGE, 10e3]
        TARGET_DOT: [0, 0, 0]
        N: 12
      condition_next: rm[0] >= 1e3
    2:
      PN:
        DESIRED: "[MAG * cos(0.001 * north - START_RANGE + OFFSET), -1, MAG * sin(0.001 * north - START_RANGE + OFFSET)]"
        TIME_CONST: 5.0
      speed_controller:
        DESIRED: 200.0
        TIME_CONST: 100.0
      condition_next: range <= 2e3
    # 5:
    #   pronav:
    #     TARGET: [0, 0, 0]
    #     TARGET_DOT: [0, 0, 0]
    #     N: 4.0


plot:
  YZ:
    x_axis: 'north'
    y_axis: 'alt'
  # XY:
  #   x_axis: 'north'
  #   y_axis: 'east'
  Speed:
    x_axis: 'north'
    y_axis: 'speed'
  G:
    x_axis: 'north'
    y_axis: 'G'
