init:
  dt: 0.01
  t_span: [0, 500]
  R0: [0, 60e3, 10e3]
  V0: [0, -100, 0]


G_LIMIT: 14.0


guidance:
  phase:
    0:
      condition_next: range <= 42e3
    1:
      # PN:
      #   DESIRED: [1, 0, 0]
      #   TIME_CONST: 2.0
      pronav:
        TARGET: [2e3, 40e3, 10e3]
        TARGET_DOT: [0, 0, 0]
        N: 12
      condition_next: rm[0] >= 2e3
    2:
      PN:
        DESIRED: "[3 * cos(0.001 * rm[1] - 40e3 - pi/1.5), -1, 3 * sin(0.001 * rm[1] - 40e3 - pi/1.5)]"
        TIME_CONST: 5.0
      # speed_controller:
      #   DESIRED: 200.0
      #   TIME_CONST: 5.0
      # condition_next: range <= 2e3
    # 5:
    #   pronav:
    #     TARGET: [0, 0, 0]
    #     TARGET_DOT: [0, 0, 0]
    #     N: 4.0


plot:
  YZ:
    x_axis: 'north'
    y_axis: 'alt'
  XY:
    x_axis: 'north'
    y_axis: 'east'
  Speed:
    x_axis: 'north'
    y_axis: 'speed'
  G:
    x_axis: 'north'
    y_axis: 'G'
