init:
  dt: 0.01
  t_span: [0, 200]
  R0: [0, 60e3, 10e3]
  V0: [0, -100, 0]


G_LIMIT: 14.0


guidance:
  phase:
    0:
      condition_next: t >= 10.0
    1:
      PN:
        DESIRED: [1, 0, 0]
        TIME_CONST: 2.0
      condition_next: t >= 11.0
    2:
      PN:
        DESIRED: "[cos(0.1 * t + pi/8), -1, sin(0.1 * t + pi/8)]"
        TIME_CONST: 5.0
      # speed_controller:
      #   DESIRED: 200.0
      #   TIME_CONST: 5.0
      # condition_next: range <= 2e3
    # 5:
    #   pronav:
    #     TARGET: [0, 0, 0]
    #     TARGET_DOT: [0, 0, 0]
    #     N: 4.0


plot:
  YZ:
    x_axis: 'north'
    y_axis: 'alt'
  Speed:
    x_axis: 'north'
    y_axis: 'speed'
  G:
    x_axis: 'north'
    y_axis: 'G'
