init:
  dt: 0.01
  t_span: [0, 400]
  R0: [0, 60e3, 1]

  V0: [0, -2, 0]

guidance:
  phase:
    0:
      alt_controller:
        DESIRED_ALT: 10.0
        ALT_TIME_CONST: 10.0 # (s)
        KD: 0.7
      speed_controller:
        TIME_CONST: 5.0
        VALUE: speed
        DESIRED: 200.0
      condition_next: range <= 40e3
    1:
      PN:
        TIME_CONST: 30.0
        VEL_HAT_DESIRED: [0, -cos(radians(10)), sin(radians(10))]
      condition_next: alt >= 100.0
    2:
      alt_controller:
        DESIRED_ALT: 10.0
        ALT_TIME_CONST: 3.0 # (s)
        KD: 0.5
      condition_next: range <= 20e3
    3:
      PN:
        TIME_CONST: 20.0
        VEL_HAT_DESIRED: [0, -cos(radians(10)), sin(radians(10))]
      condition_next: alt >= 65.0
    4:
      alt_controller:
        DESIRED_ALT: 10.0
        ALT_TIME_CONST: 3.0 # (s)
        KD: 0.5
      speed_controller:
        TIME_CONST: 5.0
        VALUE: speed
        DESIRED: 1000.0
      condition_next: range <= 10e3
    5:
      pronav:
        N: 4.0

    ################################
    # 0:
    #   alt_controller:
    #     ALT_RATE_LIMIT: 1000.0
    #     DESIRED_ALT: 5010
    #     ALT_TIME_CONST: 30.0 # (s)
    #     KD: 0.1
    #   speed_controller:
    #     TIME_CONST: 5.0
    #     VALUE: speed
    #     DESIRED: 200.0
    #   condition_next: alt >= 5000
    #   # condition_next: range <= 45000
    # 1:
    #   PN:
    #     TIME_CONST: 10.0
    #     VEL_HAT_DESIRED: [0, -cos(radians(15)), -sin(radians(15))]
    #   condition_next: range <= 10000
    # 2:
    #   speed_controller:
    #     TIME_CONST: 30.0
    #     VALUE: speed
    #     DESIRED: 100.0

plot:
  YZ:
    x_axis: 'north'
    y_axis: 'alt'
  Speed:
    x_axis: 'north'
    y_axis: 'speed'
