init:
  dt: 0.01
  t_span: [0, 50]
  R0: [0, 50e3, 10e3]
  V0: [0, -200, 0]

guidance:
  phase:
    # 0:
    #   alt_controller:
    #     ALT_RATE_LIMIT: 1000.0
    #     DESIRED_ALT: 4e3
    #     ALT_TIME_CONST: 20.0 # (s)
    #     KD: 1.0
    #     condition_next: range <= 40e3
    # 1:
    #   alt_controller:
    #     ALT_RATE_LIMIT: 1000.0
    #     DESIRED_ALT: 200
    #     ALT_TIME_CONST: 30.0 # (s)
    #     KD: 1.0
    ################################
    0:
      PN:
        TIME_CONST: 20.0
        # VEL_HAT_DESIRED: [0, -cos(2), 1]
        AXIS: [-1, 0, 0] # (axis of rotation)
        ANGLE: 20.0     # (deg)
      speed_controller:
        TIME_CONST: 5.0
        VALUE: speed
        DESIRED: 300.0

plot:
  YZ:
    x_axis: 'north'
    y_axis: 'alt'
  Speed:
    x_axis: 'north'
    y_axis: 'speed'
