init:
  dt: 0.01
  t_span: [0, 200]
  R0: [0, 20e3, 1]
  V0: [0, -1, 0]


G_LIMIT: 14.0


guidance:
  phase:
    0:
      # alt_controller:
      #   DESIRED_ALT: 3e3
      #   TIME_CONST: 30.0 # (s)
      #   KD: 0.5
      speed_controller:
        DESIRED: 200
        TIME_CONST: 5
      condition_next: range <= 15e3
    1:
      alt_controller:
        DESIRED_ALT: 71
        TIME_CONST: 5.0 # (s)
        KD: 0.5
      condition_next: alt >= 70
    2:
      PN:
        DESIRED: [0, 1, 0]
        TIME_CONST: 20
        ROT_AXIS: [0, 0, 1]
        G_LIMIT: [-3, 3]
      alt_controller:
        DESIRED_ALT: 70
        TIME_CONST: 20.0 # (s)
        KD: 0.5
      condition_next: t >= 200
    3:
      accelerate:
        G: 1.0


plot:
  YZ:
    x_axis: 'time'
    y_axis: 'alt'
  # XY:
  #   x_axis: 'north'
  #   y_axis: 'east'
  Speed:
    x_axis: 'time'
    y_axis: 'speed'
  G:
    x_axis: 'time'
    y_axis: 'G'
