init:
  dt: 0.01
  t_span: [0, 400]
  R0: [0, 50e3, 10]
  V0: [0, -200, 1]


G_LIMIT: 14.0


guidance:
  phase:
    0:
      alt_controller:
        DESIRED_ALT: 3e3
        TIME_CONST: 30.0 # (s)
        KD: 0.5
      speed_controller:
        TIME_CONST: 5.0
        VALUE: speed
        DESIRED: 200.0
      # condition_next: range <= 30e3
      condition_next: t >= 80.0

plot:
  YZ:
    x_axis: 'north'
    y_axis: 'alt'
  Speed:
    x_axis: 'north'
    y_axis: 'speed'
