init:
  dt: 0.01
  t_span: [0, 400]
  R0: [0, 40e3, 1]
  V0: [0, -1, 1]


G_LIMIT: 14.0


guidance:
  phase:
    0:
      alt_controller:
        DESIRED: 5010
        TIME_CONST: 15.0 # (s)
        ANGLE_LIMIT_DEG: 40.0 # (deg)
        KD: 0.3
      speed_controller:
        DESIRED: 200.0
        TIME_CONST: 5.0
      condition_next: alt >= 5000
      # condition_next: range <= 45000
    1:
      PN:
        DESIRED: [0, -cos(radians(15)), -sin(radians(15))]
        TIME_CONST: 10.0
      condition_next: range <= 10000
    2:
      speed_controller:
        DESIRED: 100.0
        TIME_CONST: 30.0


plot:
  YZ:
    x_axis: 'north'
    y_axis: 'alt'
  Speed:
    x_axis: 'north'
    y_axis: 'speed'
