name: Japl Unit Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libxcb-cursor0 \
          libxkbcommon-x11-0 \
          libxrender1 \
          libfontconfig1 \
          libxext6 \
          libx11-xcb1 \
          libxcb-glx0 \
          libxcb-keysyms1 \
          libxcb-image0 \
          libxcb-shm0 \
          libxcb-icccm4 \
          libxcb-sync1 \
          libxcb-xfixes0 \
          libxcb-shape0 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0

    - name: Test with unittest
      run: |
        pytest

    - name: Test Plotter GUI
      run: |
        # QT_DEBUG_PLUGINS=1  # QT verbose output
        xvfb-run python -m tests.Plotter.guitest_PyQtGraphPlotter
